books/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.book_list, name='book_list'),
    path('<slug>', views.book_detail, name='book_detail'),
    path('<book_slug>/<int:chapter_number>', views.chapter_detail, name='chapter_detail'),
    path('<book_slug>/<int:chapter_number>/<chapter_title>/<int:ex_number>', views.exercise_detail, name='exercise_detail'),
]

django_ecommerce_pro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('books.urls')),
    path('cart/', include('shopping_cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

books/models.py
from django.db import models
from django.shortcuts import redirect, reverse
from django.conf import settings
from django.db.models.signals import  post_save
# Create your models here.
'''author
    book
        chapter
            excercise
                solution1'''

class UserLibrary(models.Model):
    books = models.ManyToManyField('Book')
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username   

    def get_books(self):
        return self.books.all()

    class Meta:
        verbose_name = 'User Library'
        verbose_name_plural = 'User Library'

def post_user_signup_receiver(sender, instance, created, *args, **kwargs):
    if created:
        UserLibrary.objects.get_or_create(user=instance)

post_save.connect(post_user_signup_receiver, sender=settings.AUTH_USER_MODEL)

class Author(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    slug = models.SlugField(default=first_name)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ManyToManyField(Author)
    isbn = models.CharField(max_length=16)
    slug = models.SlugField(default=title)
    pub_date = models.DateField(auto_now=True)
    price = models.FloatField()
    cover = models.ImageField()

    def __str__(self):
        return self.title
    
    #def get_absolute_url(self):
        #from django.core.urlresolvers import reverse
     #   return redirect(reverse('book_list'))
    def get_absolute_url(self):
        #djanfromgo.core.urlresolvers import reverse
        return reverse('book_detail', kwargs={'slug': self.slug})

class Chapter(models.Model):
    title = models.CharField(max_length=100)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    chapter_number = models.IntegerField()

    def __str__(self):
         return self.title

    def get_absolute_url(self):
        #djanfromgo.core.urlresolvers import reverse
        return reverse('chapter_detail', kwargs={
            'book_slug': self.book.slug,
            'chapter_number': self.chapter_number
            })
     

class Exercise(models.Model):
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    exercise_number = models.IntegerField()
    pg_number = models.IntegerField()

    def __str__(self):
        return self.title
        
    def get_absolute_url(self):
        return reverse('exercise_detail', kwargs={
                'book_slug': self.chapter.book.slug,
                'chapter_number': self.chapter.chapter_number,
                'chapter_title': self.chapter.title,
                'ex_number': self.exercise_number
                })

class Solution(models.Model):
    sol_number = models.IntegerField(default=1)
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    image = models.ImageField()

    def __str__(self):
         return f"{self.exercise}--{self.pk}"
    # solution = models.TextField()

templates/base.html
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
     <div class="container">
      {% include 'navbar.html' %} 
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb p-3 mb-2 bg-light text-dark">
          <a href="{% url 'order_summary' %}"><img src="{% static 'shopping-cart.png' %}" alt=""></a>
          {%block breadcrumb%}{% endblock breadcrumb %}
        </ol>
      </nav>
      {% block content %}{% endblock content %}
     </div> 
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
</body>
</html>

templates/book_detail.html
{% extends 'base.html' %}
{% block title %}book details{% endblock title %}
{% block breadcrumb %}
<li class="breadcrumb-item">->{{tr}}</li>
<li class="breadcrumb-item"><a href="{% url 'book_list'%}">book list</a></li>
<li class="breadcrumb-item active">{{book.title}}</li>
{% endblock breadcrumb %}
{% block content %}
<div class='row'>
    <div class="main col-md-4" >
       {% include 'book_snippet.html' with book=book %}
    </div>
    <div class="aside col-md-8" >
        <div class="card"> 
            <h3 class="card-header">Chapters</h3>
            <ul class="list-group list-group-flush">
            {% for chapter in book.chapter_set.all %}
                <a href="{{chapter.get_absolute_url}}"><h5 class="card-header">Chapter {{chapter.chapter_number}}: {{chapter.title}}</h5></a>
            {% endfor %}
            </ul>
        </div>
    </div>
</div>

{%endblock content%}

templates/book_list.html
{% extends 'base.html' %}
{% block title %}book list{% endblock title %}
{% block breadcrumb %}
<li class="breadcrumb-item">->{{tr}}</li>
<li class="breadcrumb-item"><a href="#">book list</a></li>
{% endblock breadcrumb %}

{% block content %}
    <h1 class='text-center'>Browse our Books!</h1>
    <hr/>
    <div class="row">
        {% for book in book_list %}
        {% for author in book.author.all %}
            <div class='col-4'>
                <div class="card" style="width: 18rem;">
                    <h6 class="card-title text-center">{{book.title}}</h6>
                    <img src="{{book.cover.url}}" class="img-fluid" alt="...">
                    <div class="card-body">
                    <p class="card-subtitle mb-2 text-muted">Added On: <b>{{book.pub_date}}</b></p>
                   <span><p class="card-title">Written By: <br/><b>{{author}}</b></p></span>
                    <p style=color:green;>Only ${{book.price}}!</p>
                    <a href="{{book.get_absolute_url}}" class="btn btn-primary">more info!</a>
                    </div>
                </div>
            </div>  
        {% endfor %}
        {% endfor %}
    </div>
{% endblock content %}

templates/book_snippet.html
<div class='card'>
    <p class="card-title"><b>Title:</b> {{book.title}}</p>
    <img src="{{book.cover.url}}" class="card-img-top" alt="...">
    {% for author in book.author.all %}
    <p class="card-title"><b>Written By:</b> {{author}},</p>
    {% endfor %}
    <p class="card-text"><b>Published on:</b> {{book.pub_date}}</p>
    <h6 style=color:green;>Only For ${{book.price}}!</h5>
    {% if book_status != 'owned' %}
        <div class="card-footer">
            {% if book_status == 'in_cart'  %}
                <a class="card-footer btn btn-warning" href="{% url 'remove_from_cart' book.slug %}">
                remove from cart</a>

            {% else %}
                <a class="card-footer btn btn-warning" href="{% url 'add_to_cart' book.slug %}">
                add to cart</a>
            {% endif %}
        </div>
    {% endif %}
</div>

templates/chapter_detail.html
{% extends 'base.html' %}
{% block title %}{{chapter.title}}{% endblock title %}
{% block breadcrumb %}
    <li class="breadcrumb-item">->{{tr}}</li>
    <li class="breadcrumb-item"><a href="{% url 'book_list'%}">book list</a></li>
    <li class="breadcrumb-item"><a href="{{chapter.book.get_absolute_url}}">{{chapter.book.title}}</a></li>
    <li class="breadcrumb-item active">{{chapter.title}}</li>
{% endblock breadcrumb %}
{% block content %}

<div class='row'>
    <div class="main col-md-4" >
      {% include 'book_snippet.html' with book=chapter.book %}
    </div>
    <div class="aside col-md-8" >
        <div class="card"> 
            <h3 class="card-header">Exercises</h3>
            <ul class="list-group list-group-flush">
            {% for exercise in chapter.exercise_set.all %}
                <a href="{{exercise.get_absolute_url}}"><h5 class="card-header">Exercise {{exercise.exercise_number}}: {{exercise.title}}</h5></a>
            {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock content %}

templates/exercise_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{exercise.title}}{% endblock title %}
{% block breadcrumb %} 
    <li class="breadcrumb-item">->{{tr}}</li>
    <li class="breadcrumb-item"><a href="{% url 'book_list'%}">book list</a></li>
    <li class="breadcrumb-item"><a href="{{exercise.chapter.book.get_absolute_url}}">{{exercise.chapter.book.title}}</a></li>
    <li class="breadcrumb-item"><a href="{{exercise.chapter.get_absolute_url}}">{{exercise.chapter.title}}</a></li>
    <li class="breadcrumb-item active">{{exercise.title}}</li>
{% endblock breadcrumb %}
{% block content %}

<div class='row'>
    <div class="main col-md-4" >
        {% include 'book_snippet.html' with book=exercise.chapter.book %}
    </div>
    <div class="aside col-md-8" >
        <div class="card">
            <h3 class="card-header">Solutions</h3>
                {% if exercise.chapter.book in request.user.userlibrary.books.all  %}
                {% for solution in exercise.solution_set.all %}
                    <div class="accordion" id="toggle{{solution.sol_number}}">
                        <div class="accordion-item">
                        <h2 class="accordion-header" id="headingOne">
                            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                Solution {{solution.sol_number}}
                            </button>
                        </h2>
                        <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#toggle{{solution.sol_number}}">
                            <div class="accordion-body">
                                <img class="img-fluid" src="{{solution.image.url}}" alt="">
                            </div>
                        </div>
                        </div>
                    </div>    
                {% endfor %}
                {% else %}
                    <div class="text-center">
                        <h4>You must purchase this book to view the solutions.<br/>
                            <a href="#">Purchase this book</a></h4>
                        <img src="{% static 'stop_hand.webp' %}" height="" alt="">
                    </div>               
                {% endif %}
        </div>
    </div>
</div>

{% endblock content %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="#">Home</a>
            </li>  
          {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_signup' %}">Signup</a>
            </li>  
          {% endif %}
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

templates/order_summary.html
{% extends 'base.html' %}
{% block title %}order summary{% endblock title %}
{% block content %}

<h1>Order Summary</h1>
<table class="table table-hover table-bordered text-center">
    <tr>
       <th>no.</th>
       <th>title</th> 
       <th>sub total</th>
    </tr>

       {% for item in order.items.all %}
       <tr>
        <td>{{forloop.counter}}</td>   
        <td>{{item.books.title}} <a href="{% url 'remove_from_cart' item.books.slug %}">DEL</a></td>
        <td>{{item.books.price}}</td>
       </tr>
       {% empty %}
        <tr>
            <td colspan='3'>There are no items in your cart</td>
        </tr>
       {% endfor %}
       <tr>
        <td colspan="2">
           <strong class="pull-right">Order Total:</strong>
        </td>
        <td colspan="1">
            <strong class="pull-right">$  {{order.get_total}}</strong>
         </td>
       </tr>
       {% if order.get_total %}
        <tr>
            <td colspan="3">
                <a class="btn btn-warning" href="{% url 'book_list' %}">Continue Shopping</a>
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <a class="btn btn-primary" href="{% url 'book_list' %}">Checkout</a>
            </td>
        </tr>
        {% else %}
         <tr>
            <td colspan="3">
                <a class="btn btn-warning" href="{% url 'book_list' %}">Add To Cart</a>
            </td>
         </tr>
       {% endif %}    
</table>

{% endblock content %}